from __future__ import annotations

import random
from datetime import datetime, timedelta, date

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger
from sqlalchemy import select
from sqlalchemy.orm import Session

from .config import settings
from .db import SessionLocal
from .models import (
    User,
    Entreprise,
    Interlocuteur,
    Campagne,
    Produit,
    Devis,
    DevisProduit,
    Vente,
    Action,
)

scheduler: BackgroundScheduler | None = None


def _pick_one(db: Session, model):
    ids = list(db.scalars(select(model.id)))
    if not ids:
        return None
    chosen_id = random.choice(ids)
    return db.get(model, chosen_id)


def _create_action(db: Session) -> None:
    user = _pick_one(db, User)
    ent = _pick_one(db, Entreprise)
    if not user or not ent:
        return

    # choix interlocuteur
    inter = db.scalar(select(Interlocuteur).where(Interlocuteur.entreprise_id == ent.id).limit(1))
    # campagne optionnelle
    camp = _pick_one(db, Campagne) if random.random() < 0.5 else None

    kinds = ["call", "email", "meeting", "linkedin"]
    statuses = ["todo", "done"]

    due_at = datetime.now() + timedelta(hours=random.randint(1, 72))
    status = random.choice(statuses)
    done_at = (datetime.now() if status == "done" else None)

    a = Action(
        owner_id=user.id,
        entreprise_id=ent.id,
        interlocuteur_id=(inter.id if inter else None),
        campagne_id=(camp.id if camp else None),
        kind=random.choice(kinds),
        status=status,
        title=f"Auto action ({datetime.now().isoformat(timespec='seconds')})",
        notes="Generated by hourly scheduler",
        due_at=due_at,
        done_at=done_at,
    )
    db.add(a)
    db.commit()


def _create_devis_and_sale_sometimes(db: Session) -> None:


    if random.random() > 0.2:
        return

    user = _pick_one(db, User)
    ent = _pick_one(db, Entreprise)
    prod = _pick_one(db, Produit)
    if not user or not ent or not prod:
        return

    inter = db.scalar(select(Interlocuteur).where(Interlocuteur.entreprise_id == ent.id).limit(1))
    camp = _pick_one(db, Campagne) if random.random() < 0.6 else None

    # creer devis
    code = f"AUTO-DEV-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    d = Devis(
        owner_id=user.id,
        entreprise_id=ent.id,
        interlocuteur_id=(inter.id if inter else None),
        campagne_id=(camp.id if camp else None),
        code=code,
        title=f"Devis auto - {ent.nom}",
        status=random.choice(["draft", "sent", "accepted"]),
        issue_date=date.today(),
        valid_until=date.today() + timedelta(days=30),
        currency=prod.currency or "EUR",
        notes="Generated by hourly scheduler",
        total_amount=None,
    )
    db.add(d)
    db.commit()
    db.refresh(d)

    # ajout 1-3 lignes (produits aléatoires)
    product_ids = list(db.scalars(select(Produit.id)))
    if not product_ids:
        return

    chosen_products = random.sample(product_ids, k=min(random.randint(1, 3), len(product_ids)))

    total = 0.0
    for pid in chosen_products:
        p = db.get(Produit, pid)
        if not p:
            continue
        qty = random.randint(1, 8)
        unit_price = float(p.unit_price) if p.unit_price is not None else random.choice([49.0, 99.0, 199.0])
        line_total = qty * unit_price
        total += line_total

        line = DevisProduit(
            devis_id=d.id,
            produit_id=p.id,
            quantity=qty,
            unit_price=unit_price,
            currency=p.currency or "EUR",
            line_total=line_total,
        )
        db.add(line)

    d.total_amount = total
    db.commit()
    db.refresh(d)

    # parfois creer vente lieee au devis
    should_create_sale = (d.status == "accepted") or (random.random() < 0.3)
    if not should_create_sale:
        return

    existing_sale = db.scalar(select(Vente).where(Vente.devis_id == d.id).limit(1))
    if existing_sale:
        return

    v = Vente(
        owner_id=user.id,
        entreprise_id=ent.id,
        interlocuteur_id=(inter.id if inter else None),
        campagne_id=(camp.id if camp else None),
        devis_id=d.id,
        reference=f"AUTO-SALE-{datetime.now().strftime('%Y%m%d-%H%M%S')}",
        amount=d.total_amount,
        currency=d.currency,
        status=random.choice(["open", "won"]),
        probability=random.choice([30, 50, 70, 90]),
        expected_close_date=date.today() + timedelta(days=random.randint(7, 45)),
        notes="Generated by hourly scheduler",
    )
    db.add(v)
    db.commit()


def hourly_crm_job() -> None:
    """
    Example of a scheduled job that runs hourly to create demo CRM data.
    """
    db: Session = SessionLocal()
    try:
        _create_action(db)
        _create_devis_and_sale_sometimes(db)
    finally:
        db.close()


def start_scheduler() -> None:
    global scheduler
    if scheduler is not None:
        return

    scheduler = BackgroundScheduler(timezone=settings.APP_TIMEZONE)

    scheduler.add_job(
        hourly_crm_job,
        trigger=IntervalTrigger(hours=1),
        # Pour tester: IntervalTrigger(minutes=1)
        id="hourly_crm_job",
        replace_existing=True,
        max_instances=1,
        coalesce=True,
    )

    scheduler.start()


def stop_scheduler() -> None:
    global scheduler
    if scheduler is not None:
        scheduler.shutdown(wait=False)
        scheduler = None
